# Generated by Django 6.1 on 2026-09-01 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('duration_days', models.IntegerField(default=28)),
                ('duration_label', models.CharField(default='4 Weeks', max_length=50)),
                ('hours_per_day', models.IntegerField(default=3)),
                ('total_hours', models.IntegerField(default=84)),
                ('course_fee', models.DecimalField(decimal_places=2, default=30000, max_digits=10)),
                ('gst_percent', models.IntegerField(default=18)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('batch_start_note', models.CharField(blank=True, default='Last Batch of 2026 — Starts 27th July', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artists/')),
                ('bio', models.TextField(blank=True)),
                ('specialities', models.CharField(default='makeup', help_text='Comma separated: makeup,hair,nails,beauty', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MakeupPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('package_type', models.CharField(choices=[('bridal', 'Bridal'), ('engagement', 'Engagement'), ('reception', 'Reception'), ('party', 'Party'), ('custom', 'Custom')], default='bridal', max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for "On Request"', max_digits=10, null=True)),
                ('price_label', models.CharField(default='On Request', max_length=100)),
                ('features', models.TextField(help_text='One feature per line')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('makeup_basic', 'Makeup - Basic'), ('makeup_hd', 'Makeup - HD Bridal'), ('makeup_airbrush', 'Makeup - Airbrush Bridal'), ('hair_basic', 'Hair - Basic Styling'), ('hair_bridal', 'Hair - Bridal'), ('nails_basic', 'Nails - Basic Manicure'), ('nails_art', 'Nails - Nail Art'), ('nails_extension', 'Nails - Extension'), ('beauty_facial', 'Beauty - Facial'), ('beauty_prebridal', 'Beauty - Pre-Bridal Package'), ('tejal_makeup', 'Tejal - Makeup Package'), ('shristee_nails', 'Shristee - Nail Art Package')], max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_label', models.CharField(blank=True, help_text='Override display e.g. "Starting ₹1,500"', max_length=100)),
                ('is_on_request', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='917879223442', max_length=20)),
                ('instagram_url', models.URLField(default='https://www.instagram.com/anshitamakeover21/')),
                ('coupon_active', models.BooleanField(default=True)),
                ('coupon_code', models.CharField(default='GLAMOUR30', max_length=50)),
                ('coupon_discount_percent', models.IntegerField(default=30)),
                ('coupon_label', models.CharField(default='Limited Time Offer on Professional Makeup Artist Program', max_length=200)),
                ('coupon_auto_by_date', models.BooleanField(default=True, help_text='Auto change coupon based on date of month')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('reset_token', models.CharField(blank=True, max_length=100)),
                ('reset_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.academycourse')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('package_type', models.CharField(choices=[('photography_premium', 'Photography - Premium'), ('photography_standard', 'Photography - Standard'), ('full_event', 'Full Event Management'), ('custom', 'Custom Package')], default='custom', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_label', models.CharField(default='On Request', max_length=100)),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('bridal', 'Bridal'), ('engagement', 'Engagement'), ('reception', 'Reception'), ('hair', 'Hair'), ('nails', 'Nails'), ('beauty', 'Beauty'), ('party', 'Party'), ('academy', 'Academy')], default='bridal', max_length=20)),
                ('instagram_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.artist')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
