# Generated by Django 5.2.7 on 2026-09-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("event_type", models.CharField(default="Royal Bride", max_length=100)),
                (
                    "location",
                    models.CharField(blank=True, default="India", max_length=100),
                ),
                ("rating", models.IntegerField(default=5)),
                ("review_text", models.TextField()),
                ("wedding_date", models.CharField(blank=True, max_length=50)),
                ("is_verified", models.BooleanField(default=True)),
                ("avatar_url", models.CharField(blank=True, max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="makeuppackage",
            name="package_type",
            field=models.CharField(
                choices=[
                    ("bridal", "Bridal Suite"),
                    ("engagement", "Engagement & Roka"),
                    ("reception", "Reception & Sangeet"),
                    ("side_makeup", "Side & Family Makeup"),
                    ("party", "Party & Festive Glam"),
                    ("hair", "Haute Hair Couture"),
                    ("nails", "Nails & Extensions"),
                    ("beauty", "Skin & Pre-Bridal"),
                    ("custom", "Custom Package"),
                ],
                default="bridal",
                max_length=20,
            ),
        ),
    ]
