# Generated by Django 5.2.7 on 2026-09-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_customerreview_alter_makeuppackage_package_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="exit_coupon_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="exit_coupon_code",
            field=models.CharField(default="SECRET10", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="exit_coupon_discount_percent",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="exit_coupon_label",
            field=models.CharField(
                default="Exclusive Secret Privilege: Extra 10% Additional Discount",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="coupon_label",
            field=models.CharField(
                default="Seasonal Privilege Offer on Bridal Suites & Packages",
                max_length=200,
            ),
        ),
    ]
