from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('academy/', views.academy, name='academy'),
    path('services/', views.services_page, name='services'),
    path('gallery/', views.gallery_page, name='gallery'),
    path('services/<int:slug>/', views.service_detail, name='service_detail'),
    path('packages/', views.packages_page, name='packages'),
    path('packages/<int:pkg_id>/', views.package_detail, name='package_detail'),
    path('travel-estimator/', views.travel_estimator, name='travel_estimator'),
    path('cart/', views.cart_page, name='cart_page'),
    path('build-your-look/', views.package_builder, name='package_builder'),
    path('api/package-builder/', views.package_builder_api, name='package_builder_api'),
    path('chatbot/', views.chatbot_page, name='chatbot_page'),
    path('set-language/', views.set_language, name='set_language'),
    path('admin-login/', views.admin_login, name='admin_login'),
    path('admin-portal/', views.admin_portal, name='admin_portal'),
    path('admin-portal/enquiries/', views.admin_booking_enquiries, name='admin_booking_enquiries'),
    path('admin-logout/', views.admin_logout_view, name='admin_logout'),
    path('api/chatbot/', views.chatbot_api, name='chatbot_api'),
    path('api/booking/', views.booking_enquiry, name='booking_enquiry'),
    path('api/coupon/', views.get_coupon_api, name='coupon_api'),
    path('api/admin/coupon/', views.admin_coupon_update, name='admin_coupon'),
    path('api/admin/price/', views.admin_price_update, name='admin_price'),
    path('api/admin/event-package/', views.admin_event_package, name='admin_event_package'),
    path('api/admin/artist/', views.admin_artist_manage, name='admin_artist'),
    path('api/admin/service/', views.admin_service_manage, name='admin_service'),
    path('api/review/submit/', views.submit_review, name='submit_review'),
    path('api/admin/review/', views.admin_review_manage, name='admin_review'),
    path('api/admin/media/', views.admin_media_manage, name='admin_media'),
    path('api/admin/studio-service/', views.admin_studio_service_manage, name='admin_studio_service'),
    path('api/admin/lookgroup/', views.admin_lookgroup_manage, name='admin_lookgroup'),
    path('api/admin/lookgroup/media/', views.admin_lookmedia_manage, name='admin_lookmedia'),
    path('api/admin/ai/', views.admin_ai_command, name='admin_ai'),
    path('api/admin/ai-command/', views.admin_ai_command, name='admin_ai_command'),
    path('api/admin/ai-status/', views.admin_ai_status, name='admin_ai_status'),
    path('api/admin/site-settings/', views.admin_site_settings_manage, name='admin_site_settings'),
    path('api/admin/package/', views.admin_package_manage, name='admin_package'),
    path('api/admin/package/<int:pkg_id>/edit/', views.admin_package_manage, name='admin_package_edit'),
    path('sinha-logos/', views.sinha_logo_studio, name='sinha_logo_studio'),
    path('artist-onboarding/', views.artist_onboarding, name='artist_onboarding'),
]

