# Generated by Django 5.2.7 on 2026-09-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sitesettings_exit_coupon_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Uploaded Photo / Image"),
                            ("instagram", "Instagram Post / Reel (Auto-Embed)"),
                            ("youtube", "YouTube Video (Auto-Embed)"),
                            ("video_file", "Direct Video File (Muted/Music MP4)"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bridal", "Bridal Suite"),
                            ("engagement", "Engagement & Roka"),
                            ("reception", "Reception & Sangeet"),
                            ("hair", "Haute Hair"),
                            ("nails", "Nail Extensions & Art"),
                            ("beauty", "Skin & Pre-Bridal"),
                            ("party", "Party Glam"),
                            ("academy", "Academy Masterclass"),
                        ],
                        default="bridal",
                        max_length=20,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("gallery", "Gallery Showcase"),
                            ("reels", "Bridal Reels & Motion"),
                            ("both", "Both Gallery & Reels"),
                        ],
                        default="gallery",
                        max_length=20,
                    ),
                ),
                ("caption", models.TextField(blank=True)),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to="media_uploads/images/"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="media_uploads/videos/"
                    ),
                ),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Instagram post/reel URL or YouTube link",
                        max_length=500,
                    ),
                ),
                (
                    "embed_code",
                    models.TextField(
                        blank=True,
                        help_text="Generated or custom embed code / video ID",
                    ),
                ),
                (
                    "views_count",
                    models.CharField(blank=True, default="25.4K+ views", max_length=50),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="gallery/"),
        ),
    ]
