# Generated by Django 5.2.7 on 2026-09-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_mediaitem_alter_galleryimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="offer_bridal_free_sides",
            field=models.IntegerField(
                default=2, help_text="Number of free side makeups with bridal booking"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="offer_combo_discount_percent",
            field=models.IntegerField(
                default=15,
                help_text="Extra discount % when booking Bridal + Engagement",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="offer_grand_combo_bundle_price",
            field=models.DecimalField(
                decimal_places=2,
                default=50000.0,
                help_text="Flat package price for Grand Royal Bridal + Engagement bundle",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="offer_next_sides_discounted_price",
            field=models.DecimalField(
                decimal_places=2,
                default=2500.0,
                help_text="Special discounted price for 3rd and 4th side makeups",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="offer_rules_active",
            field=models.BooleanField(
                default=True, help_text="Enable custom booking offer privilege rules"
            ),
        ),
    ]
