# Generated by Django 5.2.7 on 2026-09-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sitesettings_offer_bridal_free_sides_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="is_group_cover",
            field=models.BooleanField(
                default=True, help_text="Primary card shown on main grid"
            ),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="look_group_id",
            field=models.CharField(
                blank=True,
                help_text='ID to group multiple photos of the same bride/person e.g. "bengali_bride"',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="look_group_name",
            field=models.CharField(
                blank=True,
                help_text='Title for lookbook e.g. "Royal Bengali Bride (4 Looks)"',
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="makeuppackage",
            name="allow_ai_negotiation",
            field=models.BooleanField(
                default=True,
                help_text="Allow AI Concierge to negotiate on this package",
            ),
        ),
        migrations.AddField(
            model_name="makeuppackage",
            name="max_discount_percent",
            field=models.IntegerField(
                default=15,
                help_text="Maximum discount percentage AI is permitted to negotiate",
            ),
        ),
        migrations.AddField(
            model_name="makeuppackage",
            name="min_negotiated_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Absolute minimum price AI Concierge is allowed to offer",
                max_digits=10,
                null=True,
            ),
        ),
    ]
