# Generated by Django 5.2.7 on 2026-09-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_galleryimage_is_group_cover_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="travel_custom_note",
            field=models.CharField(
                default="Round-trip travel (train/air) + hotel accommodation + local transport for artist & 1 assistant provided by client. Minimum package value ₹50,000+ for outstation bookings.",
                help_text="Custom note displayed in travel widget",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="travel_far_fee_max",
            field=models.IntegerField(
                default=40000, help_text="Far outstation maximum travel fee (₹)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="travel_far_fee_min",
            field=models.IntegerField(
                default=20000, help_text="Far outstation minimum travel fee (₹)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="travel_far_label",
            field=models.CharField(
                default="Pan-India Destination (400+ km)",
                help_text="Label for far outstation zone",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="travel_near_fee_max",
            field=models.IntegerField(
                default=15000, help_text="Near outstation maximum travel fee (₹)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="travel_near_fee_min",
            field=models.IntegerField(
                default=8000, help_text="Near outstation minimum travel fee (₹)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="travel_near_label",
            field=models.CharField(
                default="Nearby Cities (100–400 km)",
                help_text="Label for near outstation zone",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="travel_same_zone_km",
            field=models.IntegerField(
                default=100,
                help_text="Radius (km) considered same zone with no extra travel charge",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="travel_widget_active",
            field=models.BooleanField(
                default=True,
                help_text="Show outstation travel estimator widget on homepage",
            ),
        ),
    ]
