# Generated by Django 5.2.7 on 2026-09-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_sitesettings_travel_custom_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpackage",
            name="category",
            field=models.CharField(
                choices=[
                    ("photography", "📸 Photography & Cinematography"),
                    ("decor", "🎪 Event Planning & Stage Decor"),
                    ("catering", "🍽️ Catering & Hospitality"),
                    ("salon", "💆 Salon & Pre-Bridal Care"),
                    ("dj", "🎶 DJ, Sound & Entertainment"),
                    ("full_event", "👑 Full Wedding Management"),
                    ("custom", "✨ Custom VIP Partner Add-on"),
                ],
                default="custom",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="eventpackage",
            name="vendor_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Base external vendor cost charged to studio",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventpackage",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Client quote price",
                max_digits=12,
                null=True,
            ),
        ),
    ]
