# Generated by Django 5.2.7 on 2026-09-16 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_eventpackage_category_eventpackage_vendor_cost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LookGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Group display name e.g. "Kuhu — Traditional Kolkata Banarasi & Chandan Art"',
                        max_length=200,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True,
                        help_text='Client or Model name e.g. "Kuhu", "Miss Rajak"',
                        max_length=100,
                    ),
                ),
                (
                    "makeup_type",
                    models.CharField(
                        blank=True,
                        help_text='Type of makeup e.g. "Traditional Bengali Mukut & Chandan", "Mauve Shimmer Cut-Crease"',
                        max_length=150,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bridal", "Bridal Suites"),
                            ("reception", "Reception & Cocktail"),
                            ("engagement", "Engagement & Roka"),
                            ("sangeet", "Sangeet & Haldi"),
                            ("hair", "Hair & Draping"),
                            ("party", "Party & Side Glam"),
                            ("nails", "Nail Artistry"),
                            ("studio", "Studio & Masterclass"),
                        ],
                        default="bridal",
                        max_length=30,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="lookgroups/covers/"
                    ),
                ),
                (
                    "cover_image_url",
                    models.CharField(
                        blank=True,
                        help_text="Fallback static image path",
                        max_length=500,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudioService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Service title e.g. "Imperial Bridal Couture & Airbrush"',
                        max_length=200,
                    ),
                ),
                (
                    "discipline",
                    models.CharField(
                        help_text='Discipline tag e.g. "SIGNATURE DISCIPLINE 01 · SACRED WEDDING DAY"',
                        max_length=150,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bridal", "Bridal Suite"),
                            ("reception", "Reception & Cocktail"),
                            ("engagement", "Engagement & Roka"),
                            ("sangeet", "Sangeet & Haldi"),
                            ("saree", "Haute Hair & Saree Draping"),
                            ("party", "Family & Bridesmaids"),
                            ("nails", "Nail Extensions & Art"),
                            ("beauty", "Skin & Pre-Bridal"),
                        ],
                        default="bridal",
                        max_length=30,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual standalone service investment in ₹",
                        max_digits=10,
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional standard discounted price in ₹",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "bundle_note",
                    models.CharField(
                        blank=True,
                        help_text='Short optional bundle tag e.g. "Save 25% with Wedding Package"',
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Concise 1-2 sentence luxury editorial description"
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True,
                        help_text="Features/inclusions list, one feature per line for dynamic admin control",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        help_text='Static or CDN fallback path e.g. "/static/core/images/curated/..."',
                        max_length=500,
                    ),
                ),
                (
                    "look_group_id",
                    models.CharField(
                        blank=True,
                        help_text="Linked look group ID for lookbook popup",
                        max_length=100,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LookMediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Uploaded Photo"),
                            ("video_file", "Direct Video File (MP4)"),
                            ("instagram", "Instagram Reel / Post (Auto Embed)"),
                            ("youtube", "YouTube Video (Auto Embed)"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to="lookgroups/media/"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="lookgroups/videos/"
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Instagram Reel/Post or YouTube URL",
                        max_length=500,
                    ),
                ),
                (
                    "embed_code",
                    models.CharField(
                        blank=True,
                        help_text="Instagram shortcode or YouTube video ID",
                        max_length=200,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.CharField(
                        blank=True,
                        help_text="Auto-fetched thumbnail for Instagram/YouTube or static path",
                        max_length=500,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="core.lookgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
