# Generated by Django 5.2.7 on 2026-09-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_lookgroup_studioservice_lookmediaitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ai_max_discount_percent",
            field=models.IntegerField(
                default=20, help_text="Maximum discount % AI is permitted to negotiate"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ai_negotiation_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable AI smart price negotiation"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ai_negotiation_instructions",
            field=models.TextField(
                blank=True,
                default="Offer complimentary side makeups first. If client asks for discount, offer 10% then up to 20% max with today-only urgency.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ai_negotiation_min_floor_percent",
            field=models.IntegerField(
                default=75,
                help_text="Minimum floor price percent (e.g. 75 means min 75% of base price)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ai_negotiation_strategy",
            field=models.CharField(
                default="balanced",
                help_text="conservative | balanced | high_conversion",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_auto_coupon_active",
            field=models.BooleanField(
                default=True,
                help_text="Automatically apply today's special discount code",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_auto_coupon_badge",
            field=models.CharField(
                default="⚡ TODAY'S EXCLUSIVE DEAL: Extra 15% VIP Privilege applied automatically today!",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_auto_coupon_code",
            field=models.CharField(
                default="TODAYVIP",
                help_text="Default auto-applied coupon code",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_auto_coupon_discount",
            field=models.IntegerField(
                default=15, help_text="Discount percent or flat discount"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_auto_coupon_type",
            field=models.CharField(
                choices=[("percent", "% Percentage"), ("flat", "₹ Flat Amount")],
                default="percent",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vip_generated_codes",
            field=models.TextField(
                blank=True,
                default="[]",
                help_text="JSON list of generated VIP access codes",
            ),
        ),
        migrations.AddField(
            model_name="studioservice",
            name="allow_ai_negotiation",
            field=models.BooleanField(
                default=True,
                help_text="Allow AI Concierge to negotiate on this service",
            ),
        ),
        migrations.AddField(
            model_name="studioservice",
            name="max_discount_percent",
            field=models.IntegerField(
                default=15,
                help_text="Max discount % AI is permitted to negotiate for this service",
            ),
        ),
        migrations.AddField(
            model_name="studioservice",
            name="min_negotiated_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Absolute minimum price AI is allowed to negotiate for this service",
                max_digits=10,
                null=True,
            ),
        ),
    ]
