# Generated by Django 5.2.7 on 2026-09-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_sitesettings_ai_max_discount_percent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="makeuppackage",
            name="price_label",
        ),
        migrations.AddField(
            model_name="makeuppackage",
            name="display_label",
            field=models.CharField(
                blank=True,
                help_text="Clean human-friendly label e.g. Bridal Sangeet Makeup",
                max_length=60,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="makeuppackage",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original MRP for strikethrough display",
                max_digits=10,
                null=True,
            ),
        ),
    ]
