# Generated by Django 5.2.7 on 2026-09-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_makeuppackage_price_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_url",
            field=models.URLField(
                blank=True, default="https://www.facebook.com/anshitamakeover21"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_url",
            field=models.URLField(
                blank=True, default="https://www.youtube.com/@anshitamakeover21"
            ),
        ),
    ]
