# Generated by Django 5.2.17 on 2026-09-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_facebook_url_sitesettings_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookgroup',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lookgroup',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='lookgroup',
            name='seo_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='lookgroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='lookmediaitem',
            name='alt_text',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='lookmediaitem',
            name='consent_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lookmediaitem',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lookmediaitem',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lookmediaitem',
            name='provider',
            field=models.CharField(blank=True, help_text='youtube, instagram, or upload', max_length=20),
        ),
    ]
