# Generated by Django 5.2.7 on 2026-09-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_sitesettings_facebook_url_sitesettings_youtube_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookgroup",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Display in top spatial 3D card fan"
            ),
        ),
        migrations.AddField(
            model_name="lookgroup",
            name="show_external_link_button",
            field=models.BooleanField(
                default=True,
                help_text='Allow visitors to see "Watch on Instagram / YouTube" buttons for this album',
            ),
        ),
        migrations.AddField(
            model_name="lookgroup",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text='URL-friendly identifier e.g. "kuhu-banarasi-bride"',
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="lookmediaitem",
            name="show_platform_link",
            field=models.BooleanField(
                default=True,
                help_text='Show "Open in Instagram/YouTube" badge for this item',
            ),
        ),
    ]
