# Generated by Django 5.2.7 on 2026-09-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_bookingenquiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lookgroup",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Show this album in the homepage featured edit"
            ),
        ),
        migrations.AlterField(
            model_name="lookgroup",
            name="show_external_link_button",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="lookmediaitem",
            name="show_platform_link",
            field=models.BooleanField(default=True),
        ),
    ]
